# This is configuration file
title: üè† Linker
description: <a href="/" style="color:white; font-weight:bold">Linker</a>. –¢—É—Ç –≥–æ–¥–Ω—ã–π –∫–æ–Ω—Ç–µ–Ω—Ç
comments: true
show_downloads: true
google_analytics: false
theme: jekyll-theme-cayman
copyright: ¬© 2018+
markdown: kramdown
highlighter: rouge
#markdown: GFM
#markdown: CommonMarkGhPages
#commonmark:
#  options: ["SMART", "FOOTNOTES"]
#  extensions: ["strikethrough", "autolink", "tables"]


plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-gist

kramdown:
  parse_span_html: true
  parse_block_html: false
