# –ü–µ—Ä–µ–º–µ–Ω–Ω—ã–µ
title: –î–æ–º–∏–∫
description: <a href="/" style="color:white; font-weight:bold">üè† –î–æ–º–∏–∫</a>. –ó–∞–º–µ—Ç–∫–∏ –æ –≤–∞–∂–Ω–æ–º
show_downloads: true
google_analytics: G-5KGG8GDK54
copyright: ¬© 20<span style="background:#0092FF;color:#fff;">18+</span>
comments: true
chtg: profi_soft
comments_channel: profi_soft

# –ö–æ–Ω—Ñ–∏–≥—É—Ä–∞—Ü–∏—è
encoding: UTF-8
theme: jekyll-theme-cayman
timezone: Europe/Kiev
markdown: kramdown
highlighter: rouge
#url: ""
#baseurl: ""

kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-redirect-from
  - jemoji
  - jekyll-paginate
  - jekyll-gist
  - rouge
# for github pages compatibility
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-relative-links
#  - jekyll-readme-index
#  - jekyll-coffeescript
#  - jekyll-gist
#  - jekyll-github-metadata
#  - jekyll-default-layout

 
# –ó–∞—Ä–∞–Ω–µ–µ –∑–∞–¥–∞–Ω–Ω—ã–µ –ø–µ—Ä–µ–º–µ–Ω–Ω—ã–µ –¥–ª—è —Ñ–∞–π–ª–æ–≤
defaults:
- scope:
    type: pages
  values:
    layout: default


exclude: [node_modules, README.md]


#markdown: GFM
#markdown: CommonMarkGhPages
#commonmark:
#  options: ["SMART", "FOOTNOTES"]
#  extensions: ["strikethrough", "autolink", "tables"]
