# This is configuration file
title: Linker
description: <a href="/" style="color:white; font-weight:bold">üè† Linker</a>. –ó–∞–º–µ—Ç–∫–∏ –æ –≤–∞–∂–Ω–æ–º
comments: true
show_downloads: true
google_analytics: false
theme: jekyll-theme-cayman
copyright: ¬© 2018+
markdown: kramdown
highlighter: rouge
#markdown: GFM
#markdown: CommonMarkGhPages
#commonmark:
#  options: ["SMART", "FOOTNOTES"]
#  extensions: ["strikethrough", "autolink", "tables"]
# baseurl: feelcame.gitgub.io/linker.pp.ua
timezone: Europe/Kiev
plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-gist

kramdown:
  parse_span_html: true
  parse_block_html: true
timezone: Europe/Kiev


chtg: profi_soft

